import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const notoSans = Noto_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${notoSans.variable} antialiased`}>
        <header className="py-4">
          <div className="container">
            <div className="flex justify-between items-center">
              <Link href="/" className="text-2xl text-slate-300 font-semibold">
                SEO TOOLS
              </Link>
              <ul className="flex gap-4">
                <li>
                  <Link href="/" className="underline">
                    重複
                  </Link>
                </li>
                <li>
                  <Link href="/combination" className="underline">
                    組み合わせ
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
